name: gottask
description: A new Flutter project.

version: 2.1.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider:
  percent_indicator:
  swipedetector:
  flutter_icons:
  flutter_slidable:
  permission_handler:
  image_picker:
  photo_view:
  sqflite:
  shared_preferences: any
  path_provider:
  flutter_audio_recorder: any
  audioplayers: any
  font_awesome_flutter:
  sleek_circular_slider:
  dotted_border:
  vibration:
  flutter_incall:
  url_launcher:
  after_layout:
  flutter_launcher_icons:
  smooth_page_indicator:
  firebase_admob:
  firebase_storage:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  animated_text_kit:
  flutter_bloc: 3.0.0
  connectivity:
  uuid:
  loading_animations:
  google_fonts: any
  regexpattern:
  in_app_purchase:
  get:
  hive:
  hive_flutter:
  zefyr: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:
  moor_generator:
  build_runner: any

flutter_native_splash:
  image: assets/icon/splash.png
  color: "44427D"
  android: false

flutter:
  uses-material-design: true

  assets:
    - assets/musics/
    - assets/png/
    - assets/icon/background(1).png
    - assets/icon/icon(1).png
    - assets/icon/google.jpg
    - assets/splash/
    - assets/tessdata/
    - assets/tessdata_config.json
  fonts:
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata/Alata-Regular.ttf
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee/ABeeZee-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: Tomorrow
      fonts:
        - asset: assets/fonts/Tomorrow/Tomorrow-Regular.ttf
        - asset: assets/fonts/Tomorrow/Tomorrow-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Tomorrow/Tomorrow-Thin.ttf
          weight: 200
    - family: Source_Sans_Pro
      fonts:
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLight.ttf
          weight: 200
  