name: gottask
description: A new Flutter project.

version: 2.0.0+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.3
  percent_indicator: ^2.1.1
  swipedetector: ^1.2.0
  flutter_icons: ^1.0.0+1
  flutter_slidable: ^0.5.4
  permission_handler: ^4.2.0+hotfix.2
  image_picker: ^0.6.3+1
  photo_view: ^0.9.1
  sqflite: ^1.2.0
  shared_preferences: any
  path_provider: ^1.6.0
  flutter_audio_recorder: any
  audioplayers: any
  font_awesome_flutter: ^8.5.0
  sleek_circular_slider: ^1.0.7
  dotted_border: ^1.0.4
  vibration: ^1.2.4
  flutter_incall: ^1.0.0
  url_launcher: ^5.4.2
  after_layout: ^1.0.7+2
  flutter_launcher_icons: ^0.7.4
  smooth_page_indicator: ^0.1.3
  firebase_admob: ^0.9.1+3
  firebase_storage: ^3.1.6
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.5.1
  animated_text_kit: ^2.0.1
  flutter_bloc: any
  connectivity: ^0.4.8+6
  uuid: ^2.0.4
  loading_animations: ^2.1.0
  google_fonts: any
  regexpattern: ^0.2.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  moor_generator: ^3.1.0
  build_runner: any

flutter_native_splash:
  image: assets/icon/splash.png
  color: "44427D"
  android: false

flutter:
  uses-material-design: true

  assets:
    - assets/musics/
    - assets/png/
    - assets/icon/
    - assets/splash/

  fonts:
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata/Alata-Regular.ttf
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee/ABeeZee-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: Tomorrow
      fonts:
        - asset: assets/fonts/Tomorrow/Tomorrow-Regular.ttf
        - asset: assets/fonts/Tomorrow/Tomorrow-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Tomorrow/Tomorrow-Thin.ttf
          weight: 200
    - family: Source_Sans_Pro
      fonts:
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-ExtraLight.ttf
          weight: 200