import 'package:get/get.dart';

class NotemonDict extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'About this app': 'About this app',
          'Sign out': 'Sign out',
          'Cancel': 'Cancel',
          'Category': 'Category',
          'Priority': 'Priority',
          'Ok': 'Ok',
          'Task': 'Task',
          'task': 'Task',
          'Todo': 'Todo',
          'Reset': 'Reset',
          'High': 'High',
          'Med': 'Med',
          'Low': 'Low',
          'All': 'All',
          'Medium': 'Medium',
          'Check': 'Check',
          'Done': 'Done',
          'Delete': 'Delete',
          'Loading': 'Loading',
          'To-do list': 'To-do list',
          'Empty to-do': 'Empty to-do',
          'Empty task': 'Empty task',
          'Task list': 'Task list',
          'Notemon is my personal project. If you like it, rate it 5 stars ^.^, or if you are not satisfied with this app, please give me a comment.':
              'Notemon is my personal project. If you like it, rate it 5 stars ^.^, or if you are not satisfied with this app, please give me a comment.',
          'Contact me': 'Contact me',
          'Copied!': 'Copied!',
          'Setting': 'Setting',
          'Preferred hand': 'Preferred hand',
          'Remove ads': 'Remove ads',
          'You can watch ads for support me':
              'You can watch ads for support me',
          'Watch ads': 'Watch ads',
          'Hold to buy': 'Hold to buy',
          'Introduction': 'Introduction',
          'Type': 'Type',
          'Weaknesses': 'Weaknesses',
          'Strength index': 'Strength index',
          'Height': 'Height',
          'Weight': 'Weight',
          'Failed to sign in': 'Failed to sign in',
          'Login': 'Login',
          'Or sign in with': 'Or sign in with',
          'No internet connection.': 'No internet connection.',
          'Sign up': 'Sign up',
          'Sign up and login': 'Sign up and login',
          'Let\'s go': 'Let\'s go',
          'Go back': 'Go back',
          'Add Task': 'Add Task',
          'Empty achieve.': 'Empty achieve.',
          'Time': 'Time',
          'Color': 'Color',
          'Achievement': 'Achievement',
          'Warning:': 'Warning:',
          'Please fill in the blank.': 'Please fill in the blank.',
          'Doing in another device': 'Doing in another device',
          "Don't distract!": "Don't distract!",
          '“Facedown your phone to start timing.”':
              '“Facedown your phone to start timing.”',
          'Doing task': 'Doing task',
          'Are you sure?': 'Are you sure?',
          'Give up': 'Give up',
          'Edit task': 'Edit task',
          'You must accept permissions': 'You must accept permissions',
          'No files': 'No files',
          'Add to-do': 'Add to-do',
          'Do not go out if recording not done.':
              'Do not go out if recording not done.',
          'Edit to-do': 'Edit to-do',
          'Rename to-do': 'Rename to-do',
          'Relax': 'Relax',
          'Hobby': 'Hobby',
          'Grocery': 'Grocery',
          'Work': 'Work',
          'Event': 'Event',
          'Reminder': 'Reminder',
          'Study': 'Study',
          'Party': 'Party',
          'Planning': 'Planning',
          'Your email': 'Email của bạn',
          'Password': 'Password',
          'Your password': 'Your password',
          'Rewrite password': 'Rewrite password',
          'Rewrite your password': 'Rewrite your password',
          'Add achievement': 'Add achievement',
          'Task name': 'Task name',
          'To-do name': 'To-do name',
          'Language': 'Language',
          'Good morning,': 'Good morning,',
          'Good afternoon,': 'Good afternoon,',
          'Good evening,': 'Good evening,',
          'Detail note': 'Detail note',
          'Note': 'Note',
        },
        'vi_VN': {
          'About this app': 'Về ứng dụng này',
          'Sign out': 'Đăng xuất',
          'Cancel': 'Hủy bỏ',
          'Category': 'Thể loại',
          'Priority': 'Ưu tiên',
          'Ok': 'Xác nhận',
          'Task': 'Công việc',
          'task': 'Công việc',
          'Todo': 'To-do',
          'Reset': 'Hủy',
          'High': 'Cao',
          'Med': 'TB',
          'Low': 'Thấp',
          'All': 'Tất cả',
          'Medium': 'Trung bình',
          'Check': 'Check',
          'Done': 'Hoàn thành',
          'Delete': 'Xóa',
          'Loading': 'Đang tải',
          'To-do list': 'Danh sách to-do',
          'Empty to-do': 'Không có to-do',
          'Empty task': 'Không có tác vụ cần làm',
          'Task list': 'Danh sách tác vụ',
          'Notemon is my personal project. If you like it, rate it 5 stars ^.^, or if you are not satisfied with this app, please give me a comment.':
              'Notemon là dự án cá nhân của tôi. Nếu bạn thích nó, hãy đánh giá nó 5 sao ^. ^, Hoặc nếu bạn không hài lòng với ứng dụng này, hãy cho tôi ý kiến.',
          'Contact me': 'Liên hệ với tôi',
          'Copied!': 'Copied!',
          'Setting': 'Cài đặt',
          'Preferred hand': 'Tay thuận',
          'Remove ads': 'Loại bỏ quảng cáo',
          'You can watch ads for support me':
              'Các bạn xem quảng cáo ủng hộ mình nha',
          'Watch ads': 'Xem quảng cáo',
          'Hold to buy': 'Giữ để mua',
          'Introduction': 'Giới thiệu',
          'Type': 'Thuộc tính',
          'Weaknesses': 'Điểm yếu',
          'Strength index': 'Chỉ số sức mạnh',
          'Height': 'Chiều cao',
          'Weight': 'Khối lượng',
          'Failed to sign in': 'Không đăng nhập được',
          'Login': 'Đăng nhập',
          'Or sign in with': 'Hoặc đăng nhập bằng',
          'No internet connection.': 'Lỗi mạng.',
          'Sign up': 'Đăng ký',
          'Sign up and login': 'Đăng ký và đăng nhập',
          'Let\'s go': 'Bắt đầu',
          'Go back': 'Quay lại',
          'Add Task': 'Thêm tác vụ',
          'Empty achieve.': 'Không có mục tiêu nào.',
          'Time': 'Thời gian',
          'Color': 'Màu sắc',
          'Achievement': 'Mục tiêu',
          'Warning:': 'Cảnh báo',
          'Please fill in the blank.': 'Vui lòng điền vào chỗ trống.',
          'Doing in another device': 'Đang thực hiện trên thiết bị khác',
          "Don't distract!": "Đừng phân tâm!",
          '“Facedown your phone to start timing.”':
              '“Úp màn hình điện thoại của bạn xuống để bắt đầu tính thời gian.”',
          'Doing task': 'Làm tác vụ',
          'Are you sure?': 'Bạn có chắc không?',
          'Give up': 'Bỏ cuộc',
          'Edit task': 'Chỉnh sửa tác vụ',
          'You must accept permissions':
              'Bạn cần cho phép các quyền để sử dụng.',
          'No files': ' Không có file nào.',
          'Add to-do': 'Thêm to-do',
          'Do not go out if recording not done.': 'Ghi âm chưa hoàn thành!',
          'Edit to-do': 'Chỉnh sửa',
          'Rename to-do': 'Đổi tên to-do',
          'Relax': 'Thư giãn',
          'Hobby': 'Sở thích',
          'Grocery': 'Việc vặt',
          'Work': 'Công việc',
          'Event': 'Sự kiện',
          'Reminder': 'Nhắc nhở',
          'Study': 'Học',
          'Party': 'Chơi',
          'Planning': 'Kế hoạch',
          'Your email': 'Email của bạn',
          'Password': 'Mật khẩu',
          'Your password': 'Mật khẩu của bạn',
          'Rewrite password': 'Nhập lại mật khẩu',
          'Rewrite your password': 'Nhập lại mật khẩu của bạn',
          'Add achievement': 'Thêm mục tiêu',
          'Task name': 'Tên tác vụ',
          'To-do name': 'Tên to-do',
          'Language': 'Ngôn ngữ',
          'Good morning,': 'Chào buổi sáng,',
          'Good afternoon,': 'Chào buổi chiều,',
          'Good evening,': 'Chào buổi tối,',
          'Detail note': 'Ghi chú chi tiết',
          'Note': 'Ghi chú',
        },
      };
}
